const data = [
  {
    "name": "Test 0",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Monterrey",
    "lat": "25.6667",
    "lng": "-100.3000"
  },
  {
    "name": "Test 1",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Guadalupe",
    "lat": "25.6775",
    "lng": "-100.2597"
  },
  {
    "name": "Test 2",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Ciudad Apodaca",
    "lat": "25.7833",
    "lng": "-100.1833"
  },
  {
    "name": "Test 3",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "San Nicolás de los Garza",
    "lat": "25.7500",
    "lng": "-100.2833"
  },
  {
    "name": "Test 4",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Ciudad General Escobedo",
    "lat": "25.7933",
    "lng": "-100.1583"
  },
  {
    "name": "Test 5",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Ciudad Benito Juárez",
    "lat": "25.6500",
    "lng": "-100.0833"
  },
  {
    "name": "Test 6",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Ciudad Santa Catarina",
    "lat": "25.6833",
    "lng": "-100.4500"
  },
  {
    "name": "Test 7",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "García",
    "lat": "25.8167",
    "lng": "-100.5833"
  },
  {
    "name": "Test 8",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "San Pedro Garza García",
    "lat": "25.6667",
    "lng": "-100.3000"
  },
  {
    "name": "Test 9",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Cadereyta Jiménez",
    "lat": "25.6000",
    "lng": "-100.0000"
  },
  {
    "name": "Test 10",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Valle Alto",
    "lat": "25.5667",
    "lng": "-100.2500"
  },
  {
    "name": "Test 11",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Linares",
    "lat": "24.8597",
    "lng": "-99.5679"
  },
  {
    "name": "Test 12",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Montemorelos",
    "lat": "25.1872",
    "lng": "-99.8267"
  },
  {
    "name": "Test 13",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Galeana",
    "lat": "24.8333",
    "lng": "-100.0667"
  },
  {
    "name": "Test 14",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Santiago",
    "lat": "25.4333",
    "lng": "-100.1333"
  },
  {
    "name": "Test 15",
    "description": "test description",
    "state": "Nuevo León",
    "status": "in_progress",
    "city": "Ciudad Sabinas Hidalgo",
    "lat": "26.5000",
    "lng": "-100.1833"
  },
  {
    "name": "Test 16",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Salinas Victoria",
    "lat": "25.9667",
    "lng": "-100.3000"
  },
  {
    "name": "Test 17",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Ciénega de Flores",
    "lat": "25.9500",
    "lng": "-100.1833"
  },
  {
    "name": "Test 18",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Ciudad Cerralvo",
    "lat": "26.0899",
    "lng": "-99.6147"
  },
  {
    "name": "Test 19",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "General Bravo",
    "lat": "25.8000",
    "lng": "-99.1667"
  },
  {
    "name": "Test 20",
    "description": "test description",
    "state": "Nuevo León",
    "status": "in_progress",
    "city": "Lampazos de Naranjo",
    "lat": "27.0250",
    "lng": "-100.5056"
  },
  {
    "name": "Test 21",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Mina",
    "lat": "26.0167",
    "lng": "-100.5167"
  },
  {
    "name": "Test 22",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Bustamante",
    "lat": "26.5333",
    "lng": "-100.5000"
  },
  {
    "name": "Test 23",
    "description": "test description",
    "state": "Nuevo León",
    "status": "in_progress",
    "city": "Iturbide",
    "lat": "24.7253",
    "lng": "-99.9000"
  },
  {
    "name": "Test 24",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "General Zuazua",
    "lat": "25.8970",
    "lng": "-100.1082"
  },
  {
    "name": "Test 25",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Carmen",
    "lat": "25.9365",
    "lng": "-100.3640"
  },
  {
    "name": "Test 26",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Anáhuac",
    "lat": "27.2446",
    "lng": "-100.1323"
  },
  {
    "name": "Test 27",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Doctor Arroyo",
    "lat": "23.6721",
    "lng": "-100.1813"
  },
  {
    "name": "Test 28",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Hidalgo",
    "lat": "25.9833",
    "lng": "-100.4500"
  },
  {
    "name": "Test 29",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Pesquería",
    "lat": "25.7833",
    "lng": "-100.0537"
  },
  {
    "name": "Test 30",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Ciudad de Allende",
    "lat": "25.2869",
    "lng": "-100.0083"
  },
  {
    "name": "Test 31",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Hualahuises",
    "lat": "24.8858",
    "lng": "-99.6728"
  },
  {
    "name": "Test 32",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "China",
    "lat": "25.7000",
    "lng": "-99.2345"
  },
  {
    "name": "Test 33",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Abasolo",
    "lat": "25.9460",
    "lng": "-100.3958"
  },
  {
    "name": "Test 34",
    "description": "test description",
    "state": "Nuevo León",
    "status": "in_progress",
    "city": "Marín",
    "lat": "25.8833",
    "lng": "-100.0333"
  },
  {
    "name": "Test 35",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "General Zaragoza",
    "lat": "23.9732",
    "lng": "-99.7723"
  },
  {
    "name": "Test 36",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Ciudad General Terán",
    "lat": "25.2667",
    "lng": "-99.6833"
  },
  {
    "name": "Test 37",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Ciudad de Villaldama",
    "lat": "26.4995",
    "lng": "-100.4251"
  },
  {
    "name": "Test 38",
    "description": "test description",
    "state": "Nuevo León",
    "status": "in_progress",
    "city": "Vallecillo",
    "lat": "26.6603",
    "lng": "-99.9874"
  },
  {
    "name": "Test 39",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Agualeguas",
    "lat": "26.3167",
    "lng": "-99.5333"
  },
  {
    "name": "Test 40",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Mier y Noriega",
    "lat": "23.4225",
    "lng": "-100.1173"
  },
  {
    "name": "Test 41",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Los Ramones",
    "lat": "25.7000",
    "lng": "-99.6167"
  },
  {
    "name": "Test 42",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "General Treviño",
    "lat": "26.2232",
    "lng": "-99.4850"
  },
  {
    "name": "Test 43",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Los Herreras",
    "lat": "25.9080",
    "lng": "-99.4048"
  },
  {
    "name": "Test 44",
    "description": "test description",
    "state": "Nuevo León",
    "status": "uncertified",
    "city": "Doctor González",
    "lat": "25.8598",
    "lng": "-99.9441"
  },
  {
    "name": "Test 45",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Higueras",
    "lat": "25.9601",
    "lng": "-100.0152"
  },
  {
    "name": "Test 46",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Parás",
    "lat": "26.5001",
    "lng": "-99.5216"
  },
  {
    "name": "Test 47",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Aramberri",
    "lat": "24.1006",
    "lng": "-99.8181"
  },
  {
    "name": "Test 48",
    "description": "test description",
    "state": "Nuevo León",
    "status": "denied",
    "city": "Melchor Ocampo",
    "lat": "26.0550",
    "lng": "-99.5438"
  },
  {
    "name": "Test 49",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Los Aldamas",
    "lat": "26.0622",
    "lng": "-99.1956"
  },
  {
    "name": "Test 50",
    "description": "test description",
    "state": "Nuevo León",
    "status": "certificate",
    "city": "Rayones",
    "lat": "25.0181",
    "lng": "-100.0732"
  },
  {
    "name": "Test 51",
    "description": "test description",
    "state": "Nuevo León",
    "status": "in_progress",
    "city": "Doctor Coss",
    "lat": "25.9333",
    "lng": "-99.1667"
  },
  

  // sasa
  {
    "name": "undefined 0100",
    "state": "Ciudad de México",
    "city": "Mexico City",
    "lat": "19.4333",
    "lng": "-99.1333",
    "status": "in_progress",
  },
  {
    "name": "undefined 1100",
    "state": "Jalisco",
    "city": "Guadalajara",
    "lat": "20.6767",
    "lng": "-103.3475",
    "status": "in_progress",
  },
  {
    "name": "undefined 2100",
    "state": "Nuevo León",
    "city": "Monterrey",
    "lat": "25.6667",
    "lng": "-100.3000",
    "status": "in_progress",
  },
  {
    "name": "undefined 3100",
    "state": "Baja California",
    "city": "Tijuana",
    "lat": "32.5250",
    "lng": "-117.0333",
    "status": "in_progress",
  },
  {
    "name": "undefined 4100",
    "state": "México",
    "city": "Ecatepec",
    "lat": "19.6097",
    "lng": "-99.0600",
    "status": "in_progress",
  },
  {
    "name": "undefined 5100",
    "state": "Puebla",
    "city": "Puebla",
    "lat": "19.0333",
    "lng": "-98.1833",
    "status": "in_progress",
  },
  {
    "name": "undefined 6100",
    "state": "Guanajuato",
    "city": "León de los Aldama",
    "lat": "21.1167",
    "lng": "-101.6833",
    "status": "in_progress",
  },
  {
    "name": "undefined 7100",
    "state": "Chihuahua",
    "city": "Juárez",
    "lat": "31.7386",
    "lng": "-106.4870",
    "status": "in_progress",
  },
  {
    "name": "undefined 8100",
    "state": "Jalisco",
    "city": "Zapopan",
    "lat": "20.7167",
    "lng": "-103.4000",
    "status": "in_progress",
  },
  {
    "name": "undefined 9100",
    "state": "México",
    "city": "Nezahualcóyotl",
    "lat": "19.4000",
    "lng": "-98.9889",
    "status": "in_progress",
  },
  {
    "name": "undefined 10100",
    "state": "México",
    "city": "Ciudad Nezahualcóyotl",
    "lat": "19.4100",
    "lng": "-99.0300",
    "status": "in_progress",
  },
  {
    "name": "undefined 11100",
    "state": "Baja California",
    "city": "Mexicali",
    "lat": "32.6633",
    "lng": "-115.4678",
    "status": "in_progress",
  },
  {
    "name": "undefined 12100",
    "state": "Aguascalientes",
    "city": "Aguascalientes",
    "lat": "21.8760",
    "lng": "-102.2960",
    "status": "in_progress",
  },
  {
    "name": "undefined 13100",
    "state": "Yucatán",
    "city": "Mérida",
    "lat": "20.9700",
    "lng": "-89.6200",
    "status": "in_progress",
  },
  {
    "name": "undefined 14100",
    "state": "Chihuahua",
    "city": "Chihuahua",
    "lat": "28.6353",
    "lng": "-106.0889",
    "status": "in_progress",
  },
  {
    "name": "undefined 15100",
    "state": "México",
    "city": "Naucalpan de Juárez",
    "lat": "19.4753",
    "lng": "-99.2378",
    "status": "in_progress",
  },
  {
    "name": "undefined 16100",
    "state": "San Luis Potosí",
    "city": "San Luis Potosí",
    "lat": "22.1511",
    "lng": "-100.9761",
    "status": "in_progress",
  },
  {
    "name": "undefined 17100",
    "state": "México",
    "city": "Toluca",
    "lat": "19.2925",
    "lng": "-99.6569",
    "status": "in_progress",
  },
  {
    "name": "undefined 18100",
    "state": "Sonora",
    "city": "Hermosillo",
    "lat": "29.0989",
    "lng": "-110.9542",
    "status": "in_progress",
  },
  {
    "name": "undefined 19100",
    "state": "Coahuila de Zaragoza",
    "city": "Saltillo",
    "lat": "25.4333",
    "lng": "-101.0000",
    "status": "in_progress",
  },
  {
    "name": "undefined 20100",
    "state": "Querétaro",
    "city": "Querétaro",
    "lat": "20.5875",
    "lng": "-100.3928",
    "status": "in_progress",
  },
  {
    "name": "undefined 21100",
    "state": "Sinaloa",
    "city": "Culiacán",
    "lat": "24.8069",
    "lng": "-107.3939",
    "status": "in_progress",
  },
  {
    "name": "undefined 22100",
    "state": "Michoacán de Ocampo",
    "city": "Morelia",
    "lat": "19.7683",
    "lng": "-101.1894",
    "status": "in_progress",
  },
  {
    "name": "undefined 23100",
    "state": "México",
    "city": "Tlalnepantla",
    "lat": "19.5367",
    "lng": "-99.1947",
    "status": "in_progress",
  },
  {
    "name": "undefined 24100",
    "state": "Quintana Roo",
    "city": "Cancún",
    "lat": "21.1606",
    "lng": "-86.8475",
    "status": "in_progress",
  },
  {
    "name": "undefined 25100",
    "state": "Tamaulipas",
    "city": "Reynosa",
    "lat": "26.0922",
    "lng": "-98.2778",
    "status": "in_progress",
  },
  {
    "name": "undefined 26100",
    "state": "Nuevo León",
    "city": "Guadalupe",
    "lat": "25.6775",
    "lng": "-100.2597",
    "status": "in_progress",
  },
  {
    "name": "undefined 27100",
    "state": "Guerrero",
    "city": "Acapulco de Juárez",
    "lat": "16.8636",
    "lng": "-99.8825",
    "status": "in_progress",
  },
  {
    "name": "undefined 28100",
    "state": "Coahuila de Zaragoza",
    "city": "Torreón",
    "lat": "25.5394",
    "lng": "-103.4486",
    "status": "in_progress",
  }

]